### ISSUE TITLE
Mapper module

### ISSUE THREAD

**Issue by Bkucera** [Bkucera/CX4230-evac-sim#1]
Fill out `Mapper.ts`
The Mapper is responsible for creating the layout of the structure. It should be able to make us some walls and exits.

Currently, there are four walls that form a barrier around the whole screen.
We need to change this to have openings (how large?) and call them `exits`. Then export the array of `exits` so that our `Persons` can find them:
```js
export const exits = []
// push the exits to the array
```
We also need to answer the question of scale. What are the dimensions? How large should the `Person` object be? This should be communicated to the whomever is implementing the `Person` class.

**Comment by adurso3** [comment]
Default implementation completed in #7
